/**
 * cookedPrompts — Demo Dataset
 *
 * ~20 synthetic mock prompt log entries for the "20 Prompts Later" demo.
 * All data is entirely fictional. No real user prompts, secrets, credentials,
 * personal data, or model answers are present.
 *
 * Uses source: "demo" and provider: "demo" per design.
 */

import type { RawImportEntry } from '../types.js';

export const DEMO_ENTRIES: readonly RawImportEntry[] = [
  {
    id: 'demo-001',
    timestamp: '2025-03-10T09:15:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-4o',
    prompt_text: 'Help me with my code',
    input_tokens: 6,
    output_tokens: 450,
    total_tokens: 456,
    estimated_cost: 0.014,
    latency_ms: 3200,
    tags: ['coding', 'vague'],
    solved_status: 'unsolved',
  },
  {
    id: 'demo-002',
    timestamp: '2025-03-10T09:22:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'claude-opus',
    prompt_text: 'Write something good',
    input_tokens: 4,
    output_tokens: 800,
    total_tokens: 804,
    estimated_cost: 0.048,
    latency_ms: 8500,
    tags: ['vague', 'expensive'],
    solved_status: 'unsolved',
  },
  {
    id: 'demo-003',
    timestamp: '2025-03-10T10:05:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'o1-preview',
    prompt_text: 'What is 2 + 2?',
    input_tokens: 5,
    output_tokens: 12,
    total_tokens: 17,
    estimated_cost: 0.003,
    latency_ms: 12000,
    tags: ['model-overkill', 'math'],
    solved_status: 'solved',
  },
  {
    id: 'demo-004',
    timestamp: '2025-03-10T10:30:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-4o',
    prompt_text: 'My API key is FAKE_API_KEY_PLACEHOLDER_DO_NOT_USE please help me debug why auth fails in my Express app when I call /api/users',
    input_tokens: 35,
    output_tokens: 600,
    total_tokens: 635,
    estimated_cost: 0.019,
    latency_ms: 4100,
    tags: ['privacy-risk', 'coding'],
    solved_status: 'solved',
  },
  {
    id: 'demo-005',
    timestamp: '2025-03-10T11:00:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'claude-sonnet',
    prompt_text: 'Refactor the following 2000-line function into smaller modules. Here is the full function: function processEverything() { /* imagine 2000 lines of context pasted here that could have been summarized */ }',
    input_tokens: 4200,
    output_tokens: 3800,
    total_tokens: 8000,
    estimated_cost: 0.12,
    latency_ms: 22000,
    tags: ['token-waste', 'coding', 'long'],
    solved_status: 'partial',
  },
  {
    id: 'demo-006',
    timestamp: '2025-03-10T11:45:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-3.5-turbo',
    prompt_text: 'Explain quantum computing, cover all known research from 1980 to present, include every algorithm, write it as a PhD thesis, add citations',
    input_tokens: 30,
    output_tokens: 4000,
    total_tokens: 4030,
    estimated_cost: 0.006,
    latency_ms: 15000,
    tags: ['overly-broad', 'unrealistic'],
    solved_status: 'partial',
  },
  {
    id: 'demo-007',
    timestamp: '2025-03-10T12:00:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'claude-sonnet',
    prompt_text: 'You are a senior TypeScript developer. Given the following interface:\n\ninterface User { id: string; name: string; email: string; }\n\nWrite a function that validates a User object, returning a typed error array. Use zod if available. Output only the function, no explanation.',
    input_tokens: 65,
    output_tokens: 120,
    total_tokens: 185,
    estimated_cost: 0.003,
    latency_ms: 1800,
    tags: ['coding', 'good-prompt', 'structured'],
    solved_status: 'solved',
    user_rating: 5,
  },
  {
    id: 'demo-008',
    timestamp: '2025-03-10T13:10:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-4o',
    prompt_text: 'Fix it',
    input_tokens: 2,
    output_tokens: 300,
    total_tokens: 302,
    estimated_cost: 0.009,
    latency_ms: 2800,
    tags: ['vague', 'no-context'],
    solved_status: 'unsolved',
    session_id: 'session-abc',
    follow_up_index: 3,
    parent_prompt_id: 'demo-007',
  },
  {
    id: 'demo-009',
    timestamp: '2025-03-10T13:30:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'o1-preview',
    prompt_text: 'Sort this list alphabetically: apple, banana, cherry',
    input_tokens: 12,
    output_tokens: 8,
    total_tokens: 20,
    estimated_cost: 0.004,
    latency_ms: 9500,
    tags: ['model-overkill', 'trivial'],
    solved_status: 'solved',
    user_rating: 2,
  },
  {
    id: 'demo-010',
    timestamp: '2025-03-10T14:00:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-4o',
    prompt_text: 'Write a project plan for building a todo app. Include tech stack, timeline, milestones, and risks. Target audience: solo developer, 2-week timeline, React + Node stack.',
    input_tokens: 45,
    output_tokens: 500,
    total_tokens: 545,
    estimated_cost: 0.016,
    latency_ms: 4500,
    tags: ['planning', 'good-prompt', 'structured'],
    solved_status: 'solved',
    user_rating: 4,
  },
  {
    id: 'demo-011',
    timestamp: '2025-03-10T14:30:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'claude-haiku',
    prompt_text: 'Summarize this meeting transcript in 3 bullet points. Focus on action items and owners. Transcript: Alice said we need to ship by Friday. Bob volunteered for the API work. Carol will handle QA.',
    input_tokens: 48,
    output_tokens: 45,
    total_tokens: 93,
    estimated_cost: 0.001,
    latency_ms: 900,
    tags: ['good-prompt', 'summarization'],
    solved_status: 'solved',
    user_rating: 5,
  },
  {
    id: 'demo-012',
    timestamp: '2025-03-10T15:00:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-4o',
    prompt_text: 'Tell me everything about dogs',
    input_tokens: 6,
    output_tokens: 2000,
    total_tokens: 2006,
    estimated_cost: 0.06,
    latency_ms: 11000,
    tags: ['vague', 'overly-broad', 'token-waste'],
    solved_status: 'partial',
  },
  {
    id: 'demo-013',
    timestamp: '2025-03-10T15:30:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-4o',
    prompt_text: 'Analyze this CSV data and produce a bar chart. Data format: name,score. Output: Python matplotlib code only, no explanation. Data:\nAlice,85\nBob,92\nCarol,78',
    input_tokens: 40,
    output_tokens: 90,
    total_tokens: 130,
    estimated_cost: 0.004,
    latency_ms: 2200,
    tags: ['data-analysis', 'good-prompt', 'coding'],
    solved_status: 'solved',
    user_rating: 4,
  },
  {
    id: 'demo-014',
    timestamp: '2025-03-10T16:00:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'claude-sonnet',
    prompt_text: 'Make it better',
    input_tokens: 3,
    output_tokens: 400,
    total_tokens: 403,
    estimated_cost: 0.006,
    latency_ms: 3500,
    tags: ['vague', 'no-context'],
    solved_status: 'unsolved',
  },
  {
    id: 'demo-015',
    timestamp: '2025-03-10T16:30:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-4o',
    prompt_text: 'My password is FAKE_PASSWORD_PLACEHOLDER_DO_NOT_USE and my database is at db.example.test:5432. Why is my SELECT query timing out?',
    input_tokens: 28,
    output_tokens: 350,
    total_tokens: 378,
    estimated_cost: 0.011,
    latency_ms: 3000,
    tags: ['privacy-risk', 'coding', 'database'],
    solved_status: 'solved',
  },
  {
    id: 'demo-016',
    timestamp: '2025-03-10T17:00:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'claude-opus',
    prompt_text: 'Draft a professional email to a client explaining a 1-week delay. Tone: apologetic but confident. Include a revised timeline. Keep under 150 words.',
    input_tokens: 35,
    output_tokens: 130,
    total_tokens: 165,
    estimated_cost: 0.01,
    latency_ms: 2500,
    tags: ['writing', 'good-prompt', 'structured'],
    solved_status: 'solved',
    user_rating: 4,
  },
  {
    id: 'demo-017',
    timestamp: '2025-03-10T17:30:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-3.5-turbo',
    prompt_text: 'Generate a regex that matches valid email addresses according to RFC 5322. Output only the regex pattern, no explanation.',
    input_tokens: 22,
    output_tokens: 40,
    total_tokens: 62,
    estimated_cost: 0.001,
    latency_ms: 800,
    tags: ['coding', 'good-prompt'],
    solved_status: 'solved',
    user_rating: 3,
  },
  {
    id: 'demo-018',
    timestamp: '2025-03-10T18:00:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'o1-preview',
    prompt_text: 'What color is the sky?',
    input_tokens: 6,
    output_tokens: 5,
    total_tokens: 11,
    estimated_cost: 0.002,
    latency_ms: 8000,
    tags: ['model-overkill', 'trivial'],
    solved_status: 'solved',
    user_rating: 1,
  },
  {
    id: 'demo-019',
    timestamp: '2025-03-10T18:30:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'claude-sonnet',
    prompt_text: 'Review this pull request diff for security issues. Focus on: SQL injection, XSS, auth bypass, secrets in code. Diff context: +const query = `SELECT * FROM users WHERE id = ${userId}`',
    input_tokens: 50,
    output_tokens: 200,
    total_tokens: 250,
    estimated_cost: 0.004,
    latency_ms: 2800,
    tags: ['coding', 'security-review', 'good-prompt'],
    solved_status: 'solved',
    user_rating: 5,
  },
  {
    id: 'demo-020',
    timestamp: '2025-03-10T19:00:00Z',
    source: 'demo',
    provider: 'demo',
    model_used: 'gpt-4o',
    prompt_text: 'Do the thing from last time',
    input_tokens: 7,
    output_tokens: 250,
    total_tokens: 257,
    estimated_cost: 0.008,
    latency_ms: 2600,
    tags: ['vague', 'no-context', 'missing-reference'],
    solved_status: 'unsolved',
    session_id: 'session-xyz',
    follow_up_index: 0,
  },
] as const;
