/**
 * cookedPrompts — Local Model Recommendation Catalog
 *
 * Static local seed catalog for capability-first recommendations.
 *
 * Privacy and freshness boundary:
 * - No network calls.
 * - No provider API calls.
 * - No live pricing calls.
 * - No benchmark scraping.
 * - Entries are local metadata only and may become stale.
 * - `known_as_of` and pricing metadata must be used to communicate freshness.
 * - Region/origin is metadata for user choice and compliance, not a ranking signal.
 *
 * Maintenance notes:
 * - Entries represent model FAMILIES, not individual model versions.
 * - `representative_model_ids` are examples only and must be verified before
 *   production routing.
 * - Exact token pricing is intentionally omitted from this seed. Entries rely on
 *   the broad `cost_class` signal. Pricing may be added later ONLY when
 *   source-checked, and must then carry `pricing_known_as_of`.
 * - Coverage is a maintainable seed, not a guarantee of exhaustive or current
 *   availability. Update this file during a catalog refresh.
 */

import type { ModelCatalogEntry } from './types.js';

/** Date this seed catalog was last reviewed. */
export const MODEL_CATALOG_KNOWN_AS_OF = '2026-07-04';

/** Shared, value-free source note applied to seed entries. */
const SEED_SOURCE_NOTE =
  'Seeded from public provider model documentation; verify names, availability, and pricing during a catalog refresh before production routing.';

/** Shared availability caution for seed entries. */
const SEED_AVAILABILITY_NOTE =
  'Availability, tiers, and model IDs change frequently; verify before routing.';

export const LOCAL_MODEL_CATALOG: readonly ModelCatalogEntry[] = [
  // ----------------------------------------------------------------------
  // Frontier / global families
  // ----------------------------------------------------------------------
  {
    id: 'openai-gpt-frontier',
    provider: 'OpenAI',
    model_family: 'GPT frontier',
    representative_model_ids: ['gpt-4o', 'gpt-4.1', 'o3'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['frontier_reasoning', 'high_quality', 'multimodal', 'coding_specialist'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'high',
    speed_class: 'balanced',
    quality_class: 'frontier',
    reasoning_class: 'frontier',
    privacy_notes: 'Hosted proprietary API; do not route sensitive prompts without review.',
    safety_notes: 'Apply safety posture before candidate selection.',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'openai-gpt-fast',
    provider: 'OpenAI',
    model_family: 'GPT fast/mini/nano',
    representative_model_ids: ['gpt-4o-mini', 'gpt-4.1-mini', 'gpt-4.1-nano'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['basic_fast', 'balanced_general'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'fast',
    quality_class: 'strong',
    reasoning_class: 'standard',
    privacy_notes: 'Hosted proprietary API; review sensitive prompts before routing.',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'openai-codex-coding',
    provider: 'OpenAI',
    model_family: 'Codex/coding',
    representative_model_ids: ['codex-family', 'o3-mini'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['coding_specialist', 'frontier_reasoning'],
    modality_tags: ['text', 'code'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    availability_notes:
      'Coding-oriented tier may not be distinctly branded; verify current naming during refresh.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'anthropic-claude-opus',
    provider: 'Anthropic',
    model_family: 'Claude Opus',
    representative_model_ids: ['claude-opus-4', 'claude-3-opus'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['frontier_reasoning', 'high_quality', 'coding_specialist', 'long_context'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'high',
    speed_class: 'balanced',
    quality_class: 'frontier',
    reasoning_class: 'frontier',
    privacy_notes: 'Hosted proprietary API; review sensitive prompts before routing.',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'anthropic-claude-sonnet',
    provider: 'Anthropic',
    model_family: 'Claude Sonnet',
    representative_model_ids: ['claude-sonnet-4', 'claude-3-5-sonnet'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['balanced_general', 'high_quality', 'coding_specialist', 'long_context'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    privacy_notes: 'Hosted proprietary API; review sensitive prompts before routing.',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'anthropic-claude-haiku',
    provider: 'Anthropic',
    model_family: 'Claude Haiku',
    representative_model_ids: ['claude-haiku-3-5', 'claude-3-haiku'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['basic_fast', 'balanced_general'],
    modality_tags: ['text', 'vision'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'fast',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'google-gemini-pro',
    provider: 'Google',
    model_family: 'Gemini Pro',
    representative_model_ids: ['gemini-2.5-pro', 'gemini-1.5-pro'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['frontier_reasoning', 'high_quality', 'multimodal', 'long_context'],
    modality_tags: ['text', 'vision', 'audio', 'video', 'code'],
    context_window_class: 'very_long',
    cost_class: 'high',
    speed_class: 'balanced',
    quality_class: 'frontier',
    reasoning_class: 'frontier',
    privacy_notes: 'Hosted proprietary API; review sensitive prompts before routing.',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'google-gemini-flash',
    provider: 'Google',
    model_family: 'Gemini Flash',
    representative_model_ids: ['gemini-2.5-flash', 'gemini-1.5-flash'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['balanced_general', 'basic_fast', 'multimodal', 'long_context'],
    modality_tags: ['text', 'vision', 'audio', 'video', 'code'],
    context_window_class: 'very_long',
    cost_class: 'low',
    speed_class: 'fast',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'google-gemini-flash-lite',
    provider: 'Google',
    model_family: 'Gemini Flash-Lite',
    representative_model_ids: ['gemini-2.5-flash-lite'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['basic_fast'],
    modality_tags: ['text', 'vision'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'fast',
    quality_class: 'basic',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'xai-grok',
    provider: 'xAI',
    model_family: 'Grok',
    representative_model_ids: ['grok-4', 'grok-3'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['frontier_reasoning', 'high_quality', 'search_grounded'],
    modality_tags: ['text', 'vision', 'search'],
    context_window_class: 'long',
    cost_class: 'high',
    speed_class: 'balanced',
    quality_class: 'frontier',
    reasoning_class: 'strong',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'xai-grok-coding',
    provider: 'xAI',
    model_family: 'Grok coding/build',
    representative_model_ids: ['grok-code'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['coding_specialist', 'balanced_general'],
    modality_tags: ['text', 'code'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    availability_notes:
      'Coding-oriented tier may not be distinctly branded; verify current naming during refresh.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'meta-llama-open-weight',
    provider: 'Meta',
    model_family: 'Llama (open weight)',
    representative_model_ids: ['llama-3.3-70b', 'llama-3.1-405b'],
    region_or_origin: 'open_weight',
    access_type: 'open_weight',
    license_or_distribution: 'open_weight',
    capability_tags: ['local_or_open_weight', 'balanced_general', 'high_quality', 'coding_specialist'],
    modality_tags: ['text', 'code'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    privacy_notes: 'Open-weight; can be self-hosted for privacy-sensitive workloads.',
    availability_notes: 'Community license terms apply; verify license fit before use.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'mistral-mixtral',
    provider: 'Mistral AI',
    model_family: 'Mistral / Mixtral',
    representative_model_ids: ['mistral-large', 'mixtral-8x22b', 'mistral-small'],
    region_or_origin: 'eu',
    access_type: 'hosted_api',
    license_or_distribution: 'open_weight',
    capability_tags: ['balanced_general', 'coding_specialist', 'local_or_open_weight'],
    modality_tags: ['text', 'code'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'fast',
    quality_class: 'strong',
    reasoning_class: 'standard',
    privacy_notes: 'Several models offer open weights suitable for self-hosting.',
    availability_notes:
      'Mix of hosted and open-weight models; license varies by model. Verify per model.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'cohere-command',
    provider: 'Cohere',
    model_family: 'Command',
    representative_model_ids: ['command-r-plus', 'command-r'],
    region_or_origin: 'global',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['balanced_general', 'search_grounded', 'long_context'],
    modality_tags: ['text', 'search'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },

  // ----------------------------------------------------------------------
  // China families (region_or_origin metadata only — not a ranking signal)
  // ----------------------------------------------------------------------
  {
    id: 'alibaba-qwen-hosted',
    provider: 'Alibaba',
    model_family: 'Qwen / Tongyi (hosted: Max/Plus/Flash)',
    representative_model_ids: ['qwen-max', 'qwen-plus', 'qwen-flash'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['high_quality', 'balanced_general', 'multimodal', 'long_context'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    privacy_notes: 'Hosted API; review sensitive prompts and data-residency needs before routing.',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'alibaba-qwen-open-weight',
    provider: 'Alibaba',
    model_family: 'Qwen (open weight)',
    representative_model_ids: ['qwen2.5-72b', 'qwen2.5-coder'],
    region_or_origin: 'open_weight',
    access_type: 'open_weight',
    license_or_distribution: 'open_weight',
    capability_tags: ['local_or_open_weight', 'balanced_general', 'coding_specialist', 'high_quality'],
    modality_tags: ['text', 'code'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    privacy_notes: 'Open-weight; can be self-hosted for privacy-sensitive workloads.',
    availability_notes: 'Open-weight license terms apply; verify license fit before use.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'deepseek-v',
    provider: 'DeepSeek',
    model_family: 'DeepSeek V (general)',
    representative_model_ids: ['deepseek-v3', 'deepseek-chat'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'open_weight',
    capability_tags: ['balanced_general', 'high_quality', 'coding_specialist', 'local_or_open_weight'],
    modality_tags: ['text', 'code'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    privacy_notes: 'Hosted API available; open weights also published for self-hosting.',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'deepseek-r-reasoner',
    provider: 'DeepSeek',
    model_family: 'DeepSeek R / reasoner',
    representative_model_ids: ['deepseek-r1', 'deepseek-reasoner'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'open_weight',
    capability_tags: ['frontier_reasoning', 'high_quality', 'local_or_open_weight'],
    modality_tags: ['text', 'code'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'slow',
    quality_class: 'frontier',
    reasoning_class: 'frontier',
    privacy_notes: 'Hosted API available; open weights also published for self-hosting.',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'moonshot-kimi',
    provider: 'Moonshot AI',
    model_family: 'Kimi',
    representative_model_ids: ['kimi-k2', 'moonshot-v1-128k'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['long_context', 'balanced_general', 'coding_specialist'],
    modality_tags: ['text', 'code'],
    context_window_class: 'very_long',
    cost_class: 'medium',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    availability_notes:
      'Long-context oriented; some model variants publish open weights. Verify per variant.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'zhipu-glm',
    provider: 'Zhipu AI',
    model_family: 'GLM',
    representative_model_ids: ['glm-4-plus', 'glm-4'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'open_weight',
    capability_tags: ['balanced_general', 'high_quality', 'coding_specialist', 'local_or_open_weight'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'strong',
    availability_notes: 'Hosted API and some open-weight variants; verify per variant.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'minimax',
    provider: 'MiniMax',
    model_family: 'MiniMax',
    representative_model_ids: ['minimax-text-01', 'abab6.5'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['balanced_general', 'multimodal', 'long_context'],
    modality_tags: ['text', 'audio', 'video', 'code'],
    context_window_class: 'very_long',
    cost_class: 'low',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'baidu-ernie',
    provider: 'Baidu',
    model_family: 'ERNIE / Wenxin',
    representative_model_ids: ['ernie-4.5', 'ernie-4.0'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['balanced_general', 'high_quality', 'multimodal'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'tencent-hunyuan',
    provider: 'Tencent',
    model_family: 'Hunyuan',
    representative_model_ids: ['hunyuan-large', 'hunyuan-turbo'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'open_weight',
    capability_tags: ['balanced_general', 'multimodal', 'local_or_open_weight'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'medium',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: 'Hosted API and some open-weight variants; verify per variant.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'bytedance-doubao',
    provider: 'ByteDance',
    model_family: 'Doubao / Seed',
    representative_model_ids: ['doubao-pro', 'doubao-seed'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['balanced_general', 'basic_fast', 'multimodal'],
    modality_tags: ['text', 'vision', 'code'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'fast',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'stepfun-step',
    provider: 'StepFun',
    model_family: 'Step',
    representative_model_ids: ['step-2', 'step-1v'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['balanced_general', 'multimodal'],
    modality_tags: ['text', 'vision', 'audio'],
    context_window_class: 'long',
    cost_class: 'unknown',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'zeroone-yi',
    provider: '01.AI',
    model_family: 'Yi (open weight)',
    representative_model_ids: ['yi-large', 'yi-1.5-34b'],
    region_or_origin: 'open_weight',
    access_type: 'open_weight',
    license_or_distribution: 'open_weight',
    capability_tags: ['local_or_open_weight', 'balanced_general', 'high_quality'],
    modality_tags: ['text', 'code'],
    context_window_class: 'long',
    cost_class: 'low',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'standard',
    privacy_notes: 'Open-weight; can be self-hosted for privacy-sensitive workloads.',
    availability_notes: 'Open-weight license terms apply; a hosted API also exists. Verify per variant.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'sensetime-sensenova',
    provider: 'SenseTime',
    model_family: 'SenseNova',
    representative_model_ids: ['sensenova-5'],
    region_or_origin: 'china',
    access_type: 'hosted_api',
    license_or_distribution: 'proprietary',
    capability_tags: ['balanced_general', 'multimodal'],
    modality_tags: ['text', 'vision'],
    context_window_class: 'long',
    cost_class: 'unknown',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'standard',
    availability_notes: SEED_AVAILABILITY_NOTE,
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
  {
    id: 'baichuan',
    provider: 'Baichuan',
    model_family: 'Baichuan (open weight)',
    representative_model_ids: ['baichuan-4', 'baichuan2-13b'],
    region_or_origin: 'open_weight',
    access_type: 'open_weight',
    license_or_distribution: 'open_weight',
    capability_tags: ['local_or_open_weight', 'balanced_general'],
    modality_tags: ['text'],
    context_window_class: 'medium',
    cost_class: 'low',
    speed_class: 'balanced',
    quality_class: 'strong',
    reasoning_class: 'standard',
    privacy_notes: 'Open-weight; can be self-hosted for privacy-sensitive workloads.',
    availability_notes: 'Open-weight and hosted variants exist; verify license fit before use.',
    known_as_of: MODEL_CATALOG_KNOWN_AS_OF,
    source_notes: SEED_SOURCE_NOTE,
  },
];

/** Return the full local seed catalog (local-only, no network). */
export function getLocalModelCatalog(): readonly ModelCatalogEntry[] {
  return LOCAL_MODEL_CATALOG;
}

/** Find a catalog entry by its stable id, or undefined if not present. */
export function findModelCatalogEntryById(
  id: string,
): ModelCatalogEntry | undefined {
  return LOCAL_MODEL_CATALOG.find((entry) => entry.id === id);
}
